// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using WebManagementProyect.CInfrastructure.Persistence.AppDbContext.Configurations;
#nullable disable

namespace WebManagementProyect.CInfrastructure.Persistence.AppDbContext;

public partial class Proyectos_EPSContext : DbContext
{
    public Proyectos_EPSContext(DbContextOptions<Proyectos_EPSContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Proyecto> Proyectos { get; set; }

    public virtual DbSet<Tarea> Tareas { get; set; }

    public virtual DbSet<Token> Tokens { get; set; }

    public virtual DbSet<TokenAccesoProyecto> TokenAccesoProyectos { get; set; }

    public virtual DbSet<UsuariosAnonimo> UsuariosAnonimos { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new Configurations.ProyectoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.TareaConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.TokenConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.TokenAccesoProyectoConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.UsuariosAnonimoConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
