// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebManagementProyect.CInfrastructure.Persistence.AppDbContext;

#nullable disable

namespace WebManagementProyect.Cinfrastructure.Persistence.Migrations
{
    [DbContext(typeof(Proyectos_EPSContext))]
    [Migration("20250704045935_MotivoAnuladoisnull")]
    partial class MotivoAnuladoisnull
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebManagementProyect.CInfrastructure.Persistence.AppDbContext.Proyecto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaEliminado")
                        .HasColumnType("datetime");

                    b.Property<string>("MotivoEliminado")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NombreProyecto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Proyecto__3214EC070B5017C5");

                    b.ToTable("Proyecto", (string)null);
                });

            modelBuilder.Entity("WebManagementProyect.CInfrastructure.Persistence.AppDbContext.Tarea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("DescEstado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaEliminado")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaLimite")
                        .HasColumnType("datetime");

                    b.Property<Guid>("IdProyecto")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MotivoEliminado")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Tareas__3214EC07BE7A3AA6");

                    b.HasIndex("IdProyecto");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("WebManagementProyect.CInfrastructure.Persistence.AppDbContext.Token", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<bool>("Anulado")
                        .HasColumnType("bit");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaAnulado")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaEliminado")
                        .HasColumnType("datetime");

                    b.Property<string>("MotivoAnulado")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MotivoEliminado")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id")
                        .HasName("PK__Token__3214EC07AAB7B48D");

                    b.ToTable("Token", (string)null);
                });

            modelBuilder.Entity("WebManagementProyect.CInfrastructure.Persistence.AppDbContext.TokenAccesoProyecto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<bool>("Editar")
                        .HasColumnType("bit");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaEliminado")
                        .HasColumnType("datetime");

                    b.Property<Guid>("IdColaborador")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdCreador")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdProyecto")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Lectura")
                        .HasColumnType("bit");

                    b.Property<string>("MotivoEliminado")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TipoToken")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__TokenAcc__3214EC0757911D84");

                    b.HasIndex("IdColaborador");

                    b.HasIndex("IdCreador");

                    b.HasIndex("IdProyecto");

                    b.HasIndex("IdToken");

                    b.ToTable("TokenAccesoProyecto", (string)null);
                });

            modelBuilder.Entity("WebManagementProyect.CInfrastructure.Persistence.AppDbContext.UsuariosAnonimo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<bool>("Deshabilitado")
                        .HasColumnType("bit");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FechaDeshabilitado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaEliminado")
                        .HasColumnType("datetime");

                    b.Property<Guid>("IdToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MotivoDeshabilitado")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MotivoEliminado")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Usuarios__3214EC07FC2D0871");

                    b.HasIndex("IdToken");

                    b.ToTable("UsuariosAnonimo", (string)null);
                });

            modelBuilder.Entity("WebManagementProyect.CInfrastructure.Persistence.AppDbContext.Tarea", b =>
                {
                    b.HasOne("WebManagementProyect.CInfrastructure.Persistence.AppDbContext.Proyecto", "IdProyectoNavigation")
                        .WithMany("Tareas")
                        .HasForeignKey("IdProyecto")
                        .IsRequired()
                        .HasConstraintName("FK__Tareas__IdProyec__656C112C");

                    b.Navigation("IdProyectoNavigation");
                });

            modelBuilder.Entity("WebManagementProyect.CInfrastructure.Persistence.AppDbContext.TokenAccesoProyecto", b =>
                {
                    b.HasOne("WebManagementProyect.CInfrastructure.Persistence.AppDbContext.UsuariosAnonimo", "IdColaboradorNavigation")
                        .WithMany("TokenAccesoProyectoIdColaboradorNavigations")
                        .HasForeignKey("IdColaborador")
                        .IsRequired()
                        .HasConstraintName("FK__TokenAcce__IdCol__5FB337D6");

                    b.HasOne("WebManagementProyect.CInfrastructure.Persistence.AppDbContext.UsuariosAnonimo", "IdCreadorNavigation")
                        .WithMany("TokenAccesoProyectoIdCreadorNavigations")
                        .HasForeignKey("IdCreador")
                        .IsRequired()
                        .HasConstraintName("FK__TokenAcce__IdCre__5EBF139D");

                    b.HasOne("WebManagementProyect.CInfrastructure.Persistence.AppDbContext.Proyecto", "IdProyectoNavigation")
                        .WithMany("TokenAccesoProyectos")
                        .HasForeignKey("IdProyecto")
                        .IsRequired()
                        .HasConstraintName("FK__TokenAcce__IdPro__5DCAEF64");

                    b.HasOne("WebManagementProyect.CInfrastructure.Persistence.AppDbContext.Token", "IdTokenNavigation")
                        .WithMany("TokenAccesoProyectos")
                        .HasForeignKey("IdToken")
                        .IsRequired()
                        .HasConstraintName("FK__TokenAcce__IdTok__5CD6CB2B");

                    b.Navigation("IdColaboradorNavigation");

                    b.Navigation("IdCreadorNavigation");

                    b.Navigation("IdProyectoNavigation");

                    b.Navigation("IdTokenNavigation");
                });

            modelBuilder.Entity("WebManagementProyect.CInfrastructure.Persistence.AppDbContext.UsuariosAnonimo", b =>
                {
                    b.HasOne("WebManagementProyect.CInfrastructure.Persistence.AppDbContext.Token", "IdTokenNavigation")
                        .WithMany("UsuariosAnonimos")
                        .HasForeignKey("IdToken")
                        .IsRequired()
                        .HasConstraintName("FK__UsuariosA__IdTok__5070F446");

                    b.Navigation("IdTokenNavigation");
                });

            modelBuilder.Entity("WebManagementProyect.CInfrastructure.Persistence.AppDbContext.Proyecto", b =>
                {
                    b.Navigation("Tareas");

                    b.Navigation("TokenAccesoProyectos");
                });

            modelBuilder.Entity("WebManagementProyect.CInfrastructure.Persistence.AppDbContext.Token", b =>
                {
                    b.Navigation("TokenAccesoProyectos");

                    b.Navigation("UsuariosAnonimos");
                });

            modelBuilder.Entity("WebManagementProyect.CInfrastructure.Persistence.AppDbContext.UsuariosAnonimo", b =>
                {
                    b.Navigation("TokenAccesoProyectoIdColaboradorNavigations");

                    b.Navigation("TokenAccesoProyectoIdCreadorNavigations");
                });
#pragma warning restore 612, 618
        }
    }
}
