// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using WebManagementProyect.CInfrastructure.Persistence.AppDbContext;

namespace WebManagementProyect.CInfrastructure.Persistence.AppDbContext.Configurations
{
    public partial class TareaConfiguration : IEntityTypeConfiguration<Tarea>
    {
        public void Configure(EntityTypeBuilder<Tarea> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Tareas__3214EC07BE7A3AA6");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.Titulo)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.Estado)
                .IsRequired();
            entity.Property(e => e.DescEstado)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.FechaTarea)
                .IsRequired()
                .HasColumnType("datetime");
            entity.Property(e => e.HoraInicio)
                .IsRequired()
                .HasColumnType("time");
            entity.Property(e => e.HoraFin)
                .IsRequired()
                .HasColumnType("time");
            entity.Property(e => e.FechaLimite)
                .HasColumnType("datetime");

            entity.Property(e => e.FechaCreacion)
                .IsRequired()
                .HasColumnType("datetime");
            entity.Property(e => e.Eliminado)
               .IsRequired();
            entity.Property(e => e.FechaEliminado)
                .HasColumnType("datetime");
            entity.Property(e => e.MotivoEliminado)
                .HasMaxLength(50)
                .IsUnicode(false);


            entity.HasOne(d => d.IdProyectoNavigation).WithMany(p => p.Tareas)
                .HasForeignKey(d => d.IdProyecto)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Tareas__IdProyec__656C112C");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Tarea> entity);
    }
}
