// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using WebManagementProyect.CInfrastructure.Persistence.AppDbContext;

namespace WebManagementProyect.CInfrastructure.Persistence.AppDbContext.Configurations
{
    public partial class TokenAccesoProyectoConfiguration : IEntityTypeConfiguration<TokenAccesoProyecto>
    {
        public void Configure(EntityTypeBuilder<TokenAccesoProyecto> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__TokenAcc__3214EC0757911D84");

            entity.ToTable("TokenAccesoProyecto");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.TipoToken)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Lectura)
                .IsRequired();
            entity.Property(e => e.Editar)
                .IsRequired();

            entity.Property(e => e.FechaCreacion)
                .IsRequired()
                .HasColumnType("datetime");
            entity.Property(e => e.Eliminado)
                   .IsRequired();
            entity.Property(e => e.FechaEliminado)
                .HasColumnType("datetime");
            entity.Property(e => e.MotivoEliminado)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.IdColaboradorNavigation).WithMany(p => p.TokenAccesoProyectoIdColaboradorNavigations)
                .HasForeignKey(d => d.IdColaborador)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__TokenAcce__IdCol__5FB337D6");

            entity.HasOne(d => d.IdCreadorNavigation).WithMany(p => p.TokenAccesoProyectoIdCreadorNavigations)
                .HasForeignKey(d => d.IdCreador)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__TokenAcce__IdCre__5EBF139D");

            entity.HasOne(d => d.IdProyectoNavigation).WithMany(p => p.TokenAccesoProyectos)
                .HasForeignKey(d => d.IdProyecto)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__TokenAcce__IdPro__5DCAEF64");

            entity.HasOne(d => d.IdTokenNavigation).WithMany(p => p.TokenAccesoProyectos)
                .HasForeignKey(d => d.IdToken)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__TokenAcce__IdTok__5CD6CB2B");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TokenAccesoProyecto> entity);
    }
}
