// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using WebManagementProyect.CInfrastructure.Persistence.AppDbContext;

namespace WebManagementProyect.CInfrastructure.Persistence.AppDbContext.Configurations
{
    public partial class UsuariosAnonimoConfiguration : IEntityTypeConfiguration<UsuariosAnonimo>
    {
        public void Configure(EntityTypeBuilder<UsuariosAnonimo> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Usuarios__3214EC07FC2D0871");

            entity.ToTable("UsuariosAnonimo");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.Usuario)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Deshabilitado)
                .IsRequired();
            entity.Property(e => e.FechaDeshabilitado)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.MotivoDeshabilitado)
                .HasMaxLength(50)
                .IsUnicode(false);


            entity.Property(e => e.FechaCreacion)
                .IsRequired()
                .HasColumnType("datetime");
            entity.Property(e => e.Eliminado)
               .IsRequired();
            entity.Property(e => e.FechaEliminado)
                .HasColumnType("datetime");
            entity.Property(e => e.MotivoEliminado)
                .HasMaxLength(50)
                .IsUnicode(false);



            entity.HasOne(d => d.IdTokenNavigation).WithMany(p => p.UsuariosAnonimos)
                .HasForeignKey(d => d.IdToken)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UsuariosA__IdTok__5070F446");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<UsuariosAnonimo> entity);
    }
}
