// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebManagementProyect.CInfrastructure.Persistence.AppDbContext;

public partial class Proyecto
{
    public Guid Id { get; set; }

    public string NombreProyecto { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public bool Eliminado { get; set; }

    public DateTime? FechaEliminado { get; set; }

    public string MotivoEliminado { get; set; }

    public virtual ICollection<Tarea> Tareas { get; set; } = new List<Tarea>();

    public virtual ICollection<TokenAccesoProyecto> TokenAccesoProyectos { get; set; } = new List<TokenAccesoProyecto>();
}