// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using WebManagementProyect.ADomain.Entities;

namespace WebManagementProyect.CInfrastructure.Persistence.AppDbContext;

public partial class Proyecto: EntidadBase
{
    public string NombreProyecto { get; set; }

    public virtual ICollection<Tarea> Tareas { get; set; } = new List<Tarea>();

    public virtual ICollection<TokenAccesoProyecto> TokenAccesoProyectos { get; set; } = new List<TokenAccesoProyecto>();
}