// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using WebManagementProyect.ADomain.Entities;

namespace WebManagementProyect.CInfrastructure.Persistence.AppDbContext;

public partial class Tarea : EntidadBase
{
    public Guid IdProyecto { get; set; }

    public string Titulo { get; set; }

    public string Descripcion { get; set; }

    public TimeOnly HoraInicio { get; set; }
    public TimeOnly HoraFin { get; set; }
    public DateTime FechaTarea { get; set; }
    public int Estado { get; set; }

    public string DescEstado { get; set; }

    public DateTime? FechaLimite { get; set; }

    public virtual Proyecto IdProyectoNavigation { get; set; }
}