// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebManagementProyect.CInfrastructure.Persistence.AppDbContext;

public partial class Tarea
{
    public Guid Id { get; set; }

    public Guid IdProyecto { get; set; }

    public string Titulo { get; set; }

    public string Descripcion { get; set; }

    public bool Estado { get; set; }

    public string DescEstado { get; set; }

    public DateTime? FechaLimite { get; set; }

    public bool Eliminado { get; set; }

    public DateTime? FechaEliminado { get; set; }

    public string MotivoEliminado { get; set; }

    public virtual Proyecto IdProyectoNavigation { get; set; }
}