// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using WebManagementProyect.ADomain.Entities;

namespace WebManagementProyect.CInfrastructure.Persistence.AppDbContext;

public partial class Token: EntidadBase
{
    public string TokenHash { get; set; }

    public bool Anulado { get; set; }

    public DateTime? FechaAnulado { get; set; }

    public string MotivoAnulado { get; set; }

    public virtual ICollection<TokenAccesoProyecto> TokenAccesoProyectos { get; set; } = new List<TokenAccesoProyecto>();

    public virtual ICollection<UsuariosAnonimo> UsuariosAnonimos { get; set; } = new List<UsuariosAnonimo>();
}