// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using WebManagementProyect.ADomain.Entities;

namespace WebManagementProyect.CInfrastructure.Persistence.AppDbContext;

public partial class TokenAccesoProyecto: EntidadBase   
{
    public Guid IdToken { get; set; }

    public Guid IdProyecto { get; set; }

    public string TipoToken { get; set; }

    public Guid? IdCreador { get; set; }=null;

    public Guid? IdColaborador { get; set; }=null;

    public bool Lectura { get; set; }

    public bool Editar { get; set; }

    public virtual UsuariosAnonimo IdColaboradorNavigation { get; set; }

    public virtual UsuariosAnonimo IdCreadorNavigation { get; set; }

    public virtual Proyecto IdProyectoNavigation { get; set; }

    public virtual Token IdTokenNavigation { get; set; }
}