// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebManagementProyect.CInfrastructure.Persistence.AppDbContext;

public partial class UsuariosAnonimo
{
    public Guid Id { get; set; }

    public Guid IdToken { get; set; }

    public DateTime FechaCreacion { get; set; }

    public bool Deshabilitado { get; set; }

    public DateTime? FechaDeshabilitado { get; set; }

    public string MotivoDeshabilitado { get; set; }

    public virtual Token IdTokenNavigation { get; set; }

    public virtual ICollection<TokenAccesoProyecto> TokenAccesoProyectoIdColaboradorNavigations { get; set; } = new List<TokenAccesoProyecto>();

    public virtual ICollection<TokenAccesoProyecto> TokenAccesoProyectoIdCreadorNavigations { get; set; } = new List<TokenAccesoProyecto>();
}